// export const SET_DANH_SACH_SAN_PHAM = 'SET_DANH_SACH_SAN_PHAM'


// export const SET_SAN_PHAM_NAM = 'SET_SAN_PHAM_NAM'

// export const SET_SAN_PHAM_NAM_HUNTER = 'SET_SAN_PHAM_NAM_HUNTER'
// export const SET_SAN_PHAM_NAM_SANDAL = 'SET_SAN_PHAM_NAM_SANDAL'
// export const SET_SAN_PHAM_NAM_THE_THAO = 'SET_SAN_PHAM_NAM_THE_THAO'
// export const SET_SAN_PHAM_NAM_CHAY_BO = 'SET_SAN_PHAM_NAM_CHAY_BO'
// export const SET_SAN_PHAM_NAM_DA_BANH = 'SET_SAN_PHAM_NAM_DA_BANH'
// export const SET_SAN_PHAM_NAM_TAY = 'SET_SAN_PHAM_NAM_TAY'
// export const SET_SAN_PHAM_NAM_DEP = 'SET_SAN_PHAM_NAM_DEP'


// export const SET_SAN_PHAM_NU = 'SET_SAN_PHAM_NU'
// export const SET_SAN_PHAM_NU_HUNTER = 'SET_SAN_PHAM_NU_HUNTER'
// export const SET_SAN_PHAM_NU_GOSTO = 'SET_SAN_PHAM_NU_GOSTO'
// export const SET_SAN_PHAM_NU_SANDAL = 'SET_SAN_PHAM_NU_SANDAL'
// export const SET_SAN_PHAM_NU_BUP_BE = 'SET_SAN_PHAM_NU_BUP_BE'
// export const SET_SAN_PHAM_NU_THOI_TRANG = 'SET_SAN_PHAM_NU_THOI_TRANG'
// export const SET_SAN_PHAM_NU_CHAY_BO = 'SET_SAN_PHAM_NU_CHAY_BO'
// export const SET_SAN_PHAM_NU_THE_THAO = 'SET_SAN_PHAM_NU_THE_THAO'
// export const SET_SAN_PHAM_NU_DEP = 'SET_SAN_PHAM_NU_DEP'
// export const SET_SAN_PHAM_NU_TUI_XACH = 'SET_SAN_PHAM_NU_TUI_XACH'


// export const SET_SAN_PHAM_BE_TRAI = 'SET_SAN_PHAM_BE_TRAI'
// export const SET_SAN_PHAM_BE_TRAI_SANDAL = 'SET_SAN_PHAM_BE_TRAI_SANDAL'
// export const SET_SAN_PHAM_BE_TRAI_THE_THAO = 'SET_SAN_PHAM_BE_TRAI_THE_THAO'
// export const SET_SAN_PHAM_BE_TRAI_DEP = 'SET_SAN_PHAM_BE_TRAI_DEP'

// export const SET_SAN_PHAM_BE_GAI = 'SET_SAN_PHAM_BE_GAI'
// export const SET_SAN_PHAM_BE_GAI_BUP_BE = 'SET_SAN_PHAM_BE_GAI_BUP_BE'
// export const SET_SAN_PHAM_BE_GAI_THE_THAO = 'SET_SAN_PHAM_BE_GAI_THE_THAO'
// export const SET_SAN_PHAM_BE_GAI_SANDAL = 'SET_SAN_PHAM_BE_GAI_SANDAL'
// export const SET_SAN_PHAM_BE_GAI_DEP = 'SET_SAN_PHAM_BE_GAI_DEP'
// export const SET_SAN_PHAM_BE_GAI_TAP_DI = 'SET_SAN_PHAM_BE_GAI_TAP_DI'


// export const SET_SAN_PHAM_ALL = 'SET_SAN_PHAM_ALL'
// export const SET_CHI_TIET_SAN_PHAM = 'SET_CHI_TIET_SAN_PHAM'

module.exports = {
  SET_SAN_PHAM_NAM:'SET_SAN_PHAM_NAM',

  SET_SAN_PHAM_NAM_HUNTER:'SET_SAN_PHAM_NAM_HUNTER',
  SET_SAN_PHAM_NAM_SANDAL:'SET_SAN_PHAM_NAM_SANDAL',
  SET_SAN_PHAM_NAM_THE_THAO:'SET_SAN_PHAM_NAM_THE_THAO',
  SET_SAN_PHAM_NAM_CHAY_BO:'SET_SAN_PHAM_NAM_CHAY_BO',
  SET_SAN_PHAM_NAM_DA_BANH:'SET_SAN_PHAM_NAM_DA_BANH',
  SET_SAN_PHAM_NAM_TAY:'SET_SAN_PHAM_NAM_TAY',
  SET_SAN_PHAM_NAM_DEP:'SET_SAN_PHAM_NAM_DEP',


  SET_SAN_PHAM_NU:'SET_SAN_PHAM_NU',
  SET_SAN_PHAM_NU_HUNTER:'SET_SAN_PHAM_NU_HUNTER',
  SET_SAN_PHAM_NU_GOSTO:'SET_SAN_PHAM_NU_GOSTO',
  SET_SAN_PHAM_NU_SANDAL:'SET_SAN_PHAM_NU_SANDAL',
  SET_SAN_PHAM_NU_BUP_BE:'SET_SAN_PHAM_NU_BUP_BE',
  SET_SAN_PHAM_NU_THOI_TRANG:'SET_SAN_PHAM_NU_THOI_TRANG',
  SET_SAN_PHAM_NU_CHAY_BO:'SET_SAN_PHAM_NU_CHAY_BO',
  SET_SAN_PHAM_NU_THE_THAO:'SET_SAN_PHAM_NU_THE_THAO',
  SET_SAN_PHAM_NU_DEP:'SET_SAN_PHAM_NU_DEP',
  SET_SAN_PHAM_NU_TUI_XACH:'SET_SAN_PHAM_NU_TUI_XACH',


  SET_SAN_PHAM_BE_TRAI:'SET_SAN_PHAM_BE_TRAI',
  SET_SAN_PHAM_BE_TRAI_SANDAL:'SET_SAN_PHAM_BE_TRAI_SANDAL',
  SET_SAN_PHAM_BE_TRAI_THE_THAO:'SET_SAN_PHAM_BE_TRAI_THE_THAO',
  SET_SAN_PHAM_BE_TRAI_DEP:'SET_SAN_PHAM_BE_TRAI_DEP',

  SET_SAN_PHAM_BE_GAI:'SET_SAN_PHAM_BE_GAI',
  SET_SAN_PHAM_BE_GAI_BUP_BE:'SET_SAN_PHAM_BE_GAI_BUP_BE',
  SET_SAN_PHAM_BE_GAI_THE_THAO:'SET_SAN_PHAM_BE_GAI_THE_THAO',
  SET_SAN_PHAM_BE_GAI_SANDAL:'SET_SAN_PHAM_BE_GAI_SANDAL',
  SET_SAN_PHAM_BE_GAI_DEP:'SET_SAN_PHAM_BE_GAI_DEP',
  SET_SAN_PHAM_BE_GAI_TAP_DI:'SET_SAN_PHAM_BE_GAI_TAP_DI',
}